sudo: false

branches:
  except:
    - debian
    - khronos-registry

os:
  - linux

compiler:
  - gcc
  - clang

language:
  - c

services:
  - docker

before_install:
  - docker pull ebassi/epoxyci

before_script:
  - echo FROM ebassi/epoxyci > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t withgit .

env:
  - BUILD_OPTS=""
  - BUILD_OPTS="-Dglx=no"
  - BUILD_OPTS="-Degl=no"
  - BUILD_OPTS="-Dx11=false"

script:
  - docker run withgit /bin/sh -c "CC=$CC ./epoxy-run-tests.sh $BUILD_OPTS"
